### ISSUE TITLE
Drop Frames in some specific animations (/BUG REPORT/)

### ISSUE THREAD

**Issue by PD-Kerman** [zamprjkt/Lenovo-Thinkpad-X250-Hackintosh#1]
Hellowww a X250 Hackintosh User Here Using the newest release from your repo (OC0.8.2) ~~~ Nice project! Its a gift for all X250 users, Hackintosh lover here ,And heres a bug report:

The animations won't be that smooth in some specific places ,and even a bit laggy(especially the second one) like the one in the following video:

its like there's a frame drop from 60fps(when dragging windows or some other animations) to 20fps(the one in the video and it could be much worse at some specific time(I haven't found the rule yet its like it would get worse randomly ))
I tried to fix this on my own at first few days earlier, I tried tons of ways like modifying the platform-id , device-id and many other else and its like I didn't took much effects on it as I seen and it really would destroying the using experience , hope it could be fixed~~~

https://user-images.githubusercontent.com/100339054/176948858-82be0c17-cd3b-47c4-8c2e-bdbaa1621504.mov

https://user-images.githubusercontent.com/100339054/176948975-bc11e02e-21dc-4569-8901-21d1675e0b31.mov

*(STARED)

Thanks in advance

Best Regards

**Comment by PD-Kerman** [comment]
https://user-images.githubusercontent.com/100339054/176949680-2333fbf1-76bc-4d41-a380-c381f39c5bcc.mov


https://user-images.githubusercontent.com/100339054/176949688-9618c974-7e0c-4979-bc5b-61ceec65a299.mov

**Comment by PD-Kerman** [comment]
Hmm idk why for some reason I can't play my video which was uploaded below properly, just in case that it wouldn't, ill put my screen recordings in my repo and the name is DropFramesTroubleShooting  ;~)

**Comment by PD-Kerman** [comment]
Hoping your reply~
:~)

**Comment by zamkara** [comment]
hello,
Thank you for the report, my friend, maybe after some of my busyness is
over I'll try to trace it

Regards.

Pada tanggal Sab, 2 Jul 2022 19.37, PD-Kerman ***@***.***>
menulis:

**Comment by zamkara** [comment]
you can try adding igfxrpsc=1 in args, I haven't tested it yet but my
friend said maybe it will have an effect

Pada tanggal Sab, 2 Jul 2022 21.39, zam ***@***.***> menulis:

**Comment by PD-Kerman** [comment]
okayyyyyyy thanks for your reply :-) yea i may try it as soon as i can~

Oh, btw, just being curious~ hows those two animations working on your machine~~~ is it perfect or~? ;-) and did you get a drop frame issue on your machine~~~(global animations including those two~~~)

**Comment by zamkara** [comment]
Yes, the same on my device also feels the animation drop, but I understand
it because I don't expect much from my low specs that I haven't even
upgraded the ram yet :')

Pada tanggal Sab, 2 Jul 2022 22.48, PD-Kerman ***@***.***>
menulis:

**Comment by PD-Kerman** [comment]
> Yes, the same on my device also feels the animation drop, but I understand it because I don't expect much from my low specs that I haven't even upgraded the ram yet :') Pada tanggal Sab, 2 Jul 2022 22.48, PD-Kerman ***@***.***> menulis:
> […](#)

Ohhh, got it, and didn’t you already have an 8gb of ram ? that would be enough in general ;-) and to be honest I don’t really think that it’s caused by the memory stick cuz I was having a 4gb ram on my x250 few days ago and I recently updated it to 8GB and so do the hard drive but sadly it looks like it didn’t take almost **any** improvement  
(Except the multi-tasking for sure ;-) ) 
And hmm i actually had a doubt ‘bout if its caused by the low end CPU or (i)GPU but afterwards it looks like it wasn’t , firstly many other animations actually CAN be stable at 60fps like dragging windows or min/maximize the window from dock (it looks like it’s called genie the animation) and so do the launch bar the animations there are quite good actually and secondly there r much much perfect hackintosh cases on the older platforms like Intel Core Gen3 and Gen4, they all based on a gpu that’s not that powerful as ours (HD5500) and most importantly there actually is a model of MacBook Air that’s based on core M and with an HD5300 GPU soooooo 
In my personal opinion that might~ not being the actual problem I think ;-)


Greetings

**Comment by PD-Kerman** [comment]
> you can try adding igfxrpsc=1 in args, I haven't tested it yet but my friend said maybe it will have an effect Pada tanggal Sab, 2 Jul 2022 21.39, zam ***@***.***> menulis:
> […](#)

Helllowww there~ Good evening! I tried that this afternoon and sadly it looks like it didn’t take any effects :-( 
There must be something else wrong, maybe you could have a try then :-)

Greetings & Regards

**Comment by PD-Kerman** [comment]
> hello, Thank you for the report, my friend, maybe after some of my busyness is over I'll try to trace it Regards. Pada tanggal Sab, 2 Jul 2022 19.37, PD-Kerman ***@***.***> menulis:
> […](#)

Tried one more time just now and sadly it’s the same, don’t wanna know it isn’t working but sadly yes :-( , you could have a try on it in your spare time :D
Sooooooo any other ideas we could try ~?
Greetings & Thanks

**Comment by PD-Kerman** [comment]
Helllllowwwwww there~~~ 

any effective solutions now~~~? ;D

still looking forward to ur reply!

Best Greetings

**Comment by zamkara** [comment]
Hi, I don't know much about it, but my friends who have different devices also feel it, I think it's normal.
