### ISSUE TITLE
Trackpad update on Sonoma 14 

### ISSUE THREAD

**Issue by jack338c** [zamprjkt/Lenovo-Thinkpad-X250-Hackintosh#10]
Hello, Could you tell me which files should be udpated in opencore for Trackpad on Sonoma 14 

Thanks

you said
`Sonoma may be supported but has not been tested, Trackpad experience may be slightly different`

**Comment by xellpur** [comment]
i think you should wait for them to officially support sonoma. just go with ventura for now.

**Comment by jack338c** [comment]
got it,thank you !
