### ISSUE TITLE
I can drag but i cannot drop something.

### ISSUE THREAD

**Issue by Turbo-Virgin** [zamprjkt/Lenovo-Thinkpad-X250-Hackintosh#4]
I can drag a file (let's say an app form a .DMG installer image) but I cannot release it into the application folder. After taking my hand away from the trackpad, The app's icon stays with my cursor and will not "drop". It goes back to it's original location when "ESC" is pressed. Maybe you can edit the "DragExitDelayTime" value in the trackpad info.plist? 

Sorry if this information doesn't help, only been a week since I got into OpenCore / Hackintoshing in general :)

**Comment by zamkara** [comment]
Hello, I think there's a problem with your trackpad, or.. you changed one of the basic settings on macOS, because so far I haven't had a similar problem on my device.
