### ISSUE TITLE
ACPI: Excuted 11 blocks of module-level executable AML code freeze

### ISSUE THREAD

**Issue by sealysdorm** [zamprjkt/Lenovo-Thinkpad-X250-Hackintosh#7]
Hi, im having a problem where it gets stuck on ACPI: Excuted 11 blocks of module level executable AML code, I've tried tweaking the smbios and stuff like that, can you please release a fix where it fixes this? Thanks!

**Comment by Turbo-Virgin** [comment]
Just tried the EFI folder on BigSur, can confirm it's the same for me. however the September 19th Release works fine so I switched back to it for the time being! :)

**Comment by Cinmay2014** [comment]
Got the same issue. 
I tried Sep 19th release, and it works.
Hope the newest release could be fixed.

**Comment by zamkara** [comment]
I've made some changes in the latest release, hope that helps
