### ISSUE TITLE
WiFi detected but cant connect

### ISSUE THREAD

**Issue by MlodocianyGagnster** [zamprjkt/Lenovo-Thinkpad-X250-Hackintosh#9]
i can't my wifi working.I tried both of the kext : itlwm and airportitlwm kexts . but none of these gets my wifi working. I can get wifi signal and their names but i just can't connect.The only way i get to connect is only ethernet

**Comment by zamkara** [comment]
Routers and hotspots matter a lot, use [itlwm](https://github.com/OpenIntelWireless/HeliPort) and HeliPort.app for a more stable experience.
